name: Node.js CI
on: [push, pull_request]

jobs:
  test:
    if: contains(github.ref, 'refs/tags/') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test
